package com.springboot.mathwebapp.generatedentities;
// Generated Nov 21, 2017 6:39:25 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserRoles generated by hbm2java
 */
@Entity
@Table(name = "user_roles", catalog = "mathapplicationschema")
public class UserRoles implements java.io.Serializable {

	private int id;
	private String role;
	private Set<User> users = new HashSet<User>(0);

	public UserRoles() {
	}

	public UserRoles(int id) {
		this.id = id;
	}

	public UserRoles(int id, String role, Set<User> users) {
		this.id = id;
		this.role = role;
		this.users = users;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "role", length = 10)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRoles")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
