package com.springboot.mathwebapp.generatedentities;
// Generated Nov 21, 2017 6:39:25 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserLogs generated by hbm2java
 */
@Entity
@Table(name = "user_logs", catalog = "mathapplicationschema")
public class UserLogs implements java.io.Serializable {

	private Integer logid;
	private User user;
	private Date loginDate;

	public UserLogs() {
	}

	public UserLogs(User user, Date loginDate) {
		this.user = user;
		this.loginDate = loginDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "logid", unique = true, nullable = false)
	public Integer getLogid() {
		return this.logid;
	}

	public void setLogid(Integer logid) {
		this.logid = logid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "login_date", length = 10)
	public Date getLoginDate() {
		return this.loginDate;
	}

	public void setLoginDate(Date loginDate) {
		this.loginDate = loginDate;
	}

}
