package com.springboot.mathwebapp.generatedentities;
// Generated Nov 21, 2017 6:39:25 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserHomeworkId generated by hbm2java
 */
@Embeddable
public class UserHomeworkId implements java.io.Serializable {

	private int homeworkid;
	private int userid;

	public UserHomeworkId() {
	}

	public UserHomeworkId(int homeworkid, int userid) {
		this.homeworkid = homeworkid;
		this.userid = userid;
	}

	@Column(name = "homeworkid", nullable = false)
	public int getHomeworkid() {
		return this.homeworkid;
	}

	public void setHomeworkid(int homeworkid) {
		this.homeworkid = homeworkid;
	}

	@Column(name = "userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserHomeworkId))
			return false;
		UserHomeworkId castOther = (UserHomeworkId) other;

		return (this.getHomeworkid() == castOther.getHomeworkid()) && (this.getUserid() == castOther.getUserid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getHomeworkid();
		result = 37 * result + this.getUserid();
		return result;
	}

}
