package com.springboot.mathwebapp.generatedentities;
// Generated Nov 21, 2017 6:39:25 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserHomework generated by hbm2java
 */
@Entity
@Table(name = "user_homework", catalog = "mathapplicationschema")
public class UserHomework implements java.io.Serializable {

	private UserHomeworkId id;
	private User user;
	private String name;
	private Date deadline;
	private Integer forUserid;
	private Set<UserUploadfiles> userUploadfileses = new HashSet<UserUploadfiles>(0);

	public UserHomework() {
	}

	public UserHomework(UserHomeworkId id, User user) {
		this.id = id;
		this.user = user;
	}

	public UserHomework(UserHomeworkId id, User user, String name, Date deadline, Integer forUserid,
			Set<UserUploadfiles> userUploadfileses) {
		this.id = id;
		this.user = user;
		this.name = name;
		this.deadline = deadline;
		this.forUserid = forUserid;
		this.userUploadfileses = userUploadfileses;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "homeworkid", column = @Column(name = "homeworkid", nullable = false)),
			@AttributeOverride(name = "userid", column = @Column(name = "userid", nullable = false)) })
	public UserHomeworkId getId() {
		return this.id;
	}

	public void setId(UserHomeworkId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "name", length = 1024)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deadline", length = 10)
	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

	@Column(name = "for_userid")
	public Integer getForUserid() {
		return this.forUserid;
	}

	public void setForUserid(Integer forUserid) {
		this.forUserid = forUserid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userHomework")
	public Set<UserUploadfiles> getUserUploadfileses() {
		return this.userUploadfileses;
	}

	public void setUserUploadfileses(Set<UserUploadfiles> userUploadfileses) {
		this.userUploadfileses = userUploadfileses;
	}

}
