package com.springboot.mathwebapp.generatedviews;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Immutable;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.springboot.mathwebapp.generatedentities.User;

/**
 * UserRoles generated by hbm2java
 */
@Entity
@Table(name = "user_roles", catalog = "mathapplicationschema")
@Immutable
public class UserRolesView implements java.io.Serializable {

	private int id;
	private String role;
	private Set<UserView> users = new HashSet<UserView>(0);

	public UserRolesView() {
	}

	public UserRolesView(int id) {
		this.id = id;
	}

	public UserRolesView(int id, String role, Set<UserView> users) {
		this.id = id;
		this.role = role;
		this.users = users;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "role", length = 10)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRoles")
	public Set<UserView> getUsers() {
		return this.users;
	}

	public void setUsers(Set<UserView> users) {
		this.users = users;
	}

}
