package com.springboot.mathwebapp.generatedviews;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.hibernate.annotations.Immutable;

import com.springboot.mathwebapp.generatedentities.UserHomeworkId;

import javax.persistence.Embeddable;

/**
 * UserHomeworkId generated by hbm2java
 */
@Embeddable
@Immutable
public class UserHomeworkIdView implements java.io.Serializable {

	private int homeworkid;
	private int userid;

	public UserHomeworkIdView() {
	}

	public UserHomeworkIdView(int homeworkid, int userid) {
		this.homeworkid = homeworkid;
		this.userid = userid;
	}

	@Column(name = "homeworkid", nullable = false)
	public int getHomeworkid() {
		return this.homeworkid;
	}

	public void setHomeworkid(int homeworkid) {
		this.homeworkid = homeworkid;
	}

	@Column(name = "userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserHomeworkIdView))
			return false;
		UserHomeworkIdView castOther = (UserHomeworkIdView) other;

		return (this.getHomeworkid() == castOther.getHomeworkid()) && (this.getUserid() == castOther.getUserid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getHomeworkid();
		result = 37 * result + this.getUserid();
		return result;
	}

}
